var ar = {
  "phones": "هواتف",
  "laptops": "أجهزة كمبيوتر محمولة",
  "electronics": "إلكترونيات",
  "watches": "ساعات",
  "clothes": "ملابس",
  "shoes": "أحذية",
  "books": "كتب",
  "cosmetics": "مستحضرات تجميل",
  "Display name cannot be empty": "اسم العرض لا يمكن أن يكون فارغًا",
  "Display name must be between 3 and 20 characters":
      "يجب أن يكون اسم العرض بين 3 و20 حرفًا",
  "Please enter an email": "الرجاء إدخال بريد إلكتروني",
  "Please enter a valid email": "الرجاء إدخال بريد إلكتروني صحيح",
  "Please enter a password": "الرجاء إدخال كلمة مرور",
  "Password must be at least 6 characters long":
      "يجب أن تكون كلمة المرور مكونة من 6 أحرف على الأقل",
  "Passwords do not match": "كلمات المرور غير متطابقة",
  "Cancel": "إلغاء",
  "OK": "موافق",
  "Choose option": "اختر خيارًا",
  "Camera": "الكاميرا",
  "Gallery": "المعرض",
  "Remove": "إزالة",
  "Shop Now": "تسوق الآن",
  "Whoops": "عذرًا",
  "An error occurred": "حدث خطأ",
  "User registered successfully": "تم تسجيل المستخدم بنجاح",
  "Success": "نجاح",
  "Sign in by google": "تسجيل الدخول باستخدام جوجل",
  "Welcome back": "مرحبًا بعودتك",
  "Email address": "عنوان البريد الإلكتروني",
  "Enter Password": "أدخل كلمة المرور",
  "Forgot password": "نسيت كلمة المرور",
  "Login": "تسجيل الدخول",
  "OR CONNECT USING": "أو الاتصال باستخدام",
  "Don't have an account?": "ليس لديك حساب؟",
  "Sign up": "اشتراك",
  "Welcome": "مرحبًا",
  "Your welcome message": "رسالة الترحيب الخاصة بك",
  "User Name": "اسم المستخدم",
  "Enter User Name..": "أدخل اسم المستخدم..",
  "Email Address": "عنوان البريد الإلكتروني",
  "Enter Valid Email..": "أدخل بريدًا إلكترونيًا صحيحًا..",
  "Confirm Password": "تأكيد كلمة المرور",
  "Your cart is empty": "سلة التسوق الخاصة بك فارغة",
  "Looks like you didn": "يبدو أنك لم تقم",
  "Cart": "سلة التسوق",
  "Remove Items": "إزالة العناصر",
  "Total": "الإجمالي",
  "products": "المنتجات",
  "Checkout": "تأكيد الطلب",
  "Latest arrival": "المضافة حديثاً",
  "Categories": "الفئات",
  "Search": "بحث",
  "No Product Found": "لم يتم العثور على منتج",
  "Sucsecc": "نجاح",
  "Order has been requseted sucseccfully": "تم طلب الطلب بنجاح",
  "My Orders": "طلباتي",
  "In Cart": "في السلة",
  "Add to cart": "أضف إلى السلة",
  "About this item": "حول هذا العنصر",
  "In": "في",
  "Please login to have ultimate access":
      "الرجاء تسجيل الدخول للحصول على وصول كامل",
  "General": "عام",
  "All Orders": "طلباتي",
  "Wishlist": "المفضلة ",
  "ViewedRecently": "تمت مشاهدته مؤخرًا",
  "Settings": "الإعدادات",
  "Dark Mode": "الوضع الداكن",
  "Light Mode": "الوضع الفاتح",
  "Languages": "اللغات",
  "Logout": "تسجيل الخروج",
  "Are you sure": "هل أنت متأكد",
  "Select Language": "اختر اللغة",
  "English": "الإنجليزية",
  "Turkish": "التركية",
  "Arabic": "العربية",
  "Your wishlist is empty": "قائمة الرغبات الخاصة بك فارغة",
  "Looks like you didnot have wishlist": "يبدو أنه ليس لديك قائمة رغبات",
  "Home": "الصفحة الرئيسية",
  "Profile": "الملف الشخصي",
  'No Result Found': 'لا توجد نتائج',
  'Order ID:': 'رقم الطلب',
  'User:': 'اسم الزبون',
  'Date:': 'التاريخ',
  'Total Price:': 'القيمة الإجمالية',
  'Status:': 'الحالة',
  'Products:': 'المواد',
  'pending:': 'معلق',
  'processing:': 'جاري المعالجة',
  'shipped:': 'مشحون',
  'delivered:': 'تم التوصيل',
  'cancelled:': 'ملغى',
};
