var en = {
  'phones': 'phones',
  'laptops': 'laptops',
  'electronics': 'electronics',
  'watches': 'watches',
  'clothes': 'clothes',
  'shoes': 'shoes',
  'books': 'books',
  'cosmetics': 'cosmetics',
  'Display name cannot be empty': 'Display name cannot be empty',
  'Display name must be between 3 and 20 characters':
      'Display name must be between 3 and 20 characters',
  'Please enter an email': 'Please enter an email',
  'Please enter a valid email': 'Please enter a valid email',
  'Please enter a password': 'Please enter a password',
  'Password must be at least 6 characters long':
      'Password must be at least 6 characters long',
  'Passwords do not match': 'Passwords do not match',
  'Cancel': 'Cancel',
  'OK': 'OK',
  'Wishlist': 'Wishlist',
  'Orders': 'Orders',
  'Shop Now': 'Shop Now',
  'Looks like you didnot have any order':
      'Looks like you didnot have any order',
  'Your orders is empty': 'Your orders is empty',
  'Your wishlist is empty': 'Your wishlist is empty',
  'Looks like you didnot have wishlist': 'Looks like you didnot have wishlist',
  'Choose option': 'Choose option',
  'Camera': 'Camera',
  'Gallery': 'Gallery',
  'Remove': 'Remove',
  'Shop Now': 'Shop Now',
  'Whoops': 'Whoops',
  'An error occurred': 'An error occurred',
  'User registered successfully': 'User registered successfully',
  'Success': 'Success',
  'Sign in by google': 'Sign in by google',
  'Welcome back': 'Welcome back',
  'Email address': 'Email address',
  'Enter Password': 'Enter Password',
  'Forgot password': 'Forgot password',
  'Login': 'Login',
  'OR CONNECT USING': 'OR CONNECT USING',
  'Don\'t have an account?': 'Don\'t have an account?',
  'Sign up': 'Sign up',
  'Welcome': 'Welcome',
  'Your welcome message': 'Your welcome message',
  'User Name': 'User Name',
  'Enter User Name..': 'Enter User Name..',
  'Email Address': 'Email Address',
  'Enter Valid Email..': 'Enter Valid Email..',
  'Confirm Password': 'Confirm Password',
  'Your cart is empty': 'Your cart is empty',
  'Looks like you didn': 'Looks like you didn',
  'Cart': 'Cart',
  'Remove Items': 'Remove Items',
  'Total': 'Total',
  'products': 'products',
  'Checkout': 'Checkout',
  'Latest arrival': 'Latest arrival',
  'Categories': 'Categories',
  'Search': 'Search',
  'No Product Found': 'No Product Found',
  'Sucsecc': 'Sucsecc',
  'Order has been requseted sucseccfully':
      'Order has been requseted sucseccfully',
  'My Orders': 'My Orders',
  'In Cart': 'In Cart',
  'Add to cart': 'Add to cart',
  'About this item': 'About this item',
  'In': 'In',
  'Please login to have ultimate access':
      'Please login to have ultimate access',
  'General': 'General',
  'All Orders': 'All Orders',
  'Wishlist': 'Wishlist',
  'ViewedRecently': 'ViewedRecently',
  'Settings': 'Settings',
  'Dark Mode': 'Dark Mode',
  'Light Mode': 'Light Mode',
  'Languages': 'Languages',
  'Logout': 'Logout',
  'Are you sure': 'Are you sure',
  'Select Language': 'Select Language',
  'English': 'English',
  'Turkish': 'Turkish',
  'Arabic': 'Arabic',
  'Your wishlist is empty': 'Your wishlist is empty',
  'Looks like you didnot have wishlist': 'Looks like you didnot have wishlist',
  'Home': 'Home',
  'Profile': 'Profile',
  'No Result Found': 'No Result Found',
  'Order ID:': 'Order ID',
  'User:': 'User',
  'Date:': 'Date',
  'Total Price:': 'Total Price',
  'Status:': 'Status',
  'Products:': 'Products',
  'pending:': 'pending',
  'processing:': 'processing',
  'shipped:': 'shipped',
  'delivered:': 'delivered',
  'cancelled:': 'cancelled',
};
