var tr = {
  "phones": "telefonlar",
  "laptops": "dizüstü bilgisayarlar",
  "electronics": "elektronik",
  "watches": "saatler",
  "clothes": "giysiler",
  "shoes": "ayakkabılar",
  "books": "kitaplar",
  "cosmetics": "kozmetik",
  "Display name cannot be empty": "Görünen ad boş olamaz",
  "Display name must be between 3 and 20 characters":
      "Görünen ad 3 ile 20 karakter arasında olmalıdır",
  "Please enter an email": "Lütfen bir e-posta girin",
  "Please enter a valid email": "Lütfen geçerli bir e-posta girin",
  "Please enter a password": "Lütfen bir şifre girin",
  "Password must be at least 6 characters long":
      "Şifre en az 6 karakter uzunluğunda olmalıdır",
  "Passwords do not match": "Şifreler eşleşmiyor",
  "Cancel": "İptal",
  'Wishlist': 'Wishlist',
  'Orders': 'Orders',
  'Shop Now': 'Shop Now',
  'Looks like you didnot have any order':
      'Looks like you didnot have any order',
  'Your orders is empty': 'Your orders is empty',
  'Your wishlist is empty': 'Your wishlist is empty',
  'Looks like you didnot have wishlist': 'Looks like you didnot have wishlist',
  "OK": "Tamam",
  "Choose option": "Seçenek seçin",
  "Camera": "Kamera",
  "Gallery": "Galeri",
  "Remove": "Kaldır",
  "Shop Now": "Hemen Alışveriş Yap",
  "Whoops": "Uups",
  "An error occurred": "Bir hata oluştu",
  "User registered successfully": "Kullanıcı başarıyla kaydedildi",
  "Success": "Başarı",
  "Sign in by google": "Google ile giriş yap",
  "Welcome back": "Tekrar hoş geldiniz",
  "Email address": "E-posta adresi",
  "Enter Password": "Şifre Girin",
  "Forgot password": "Şifremi unuttum",
  "Login": "Giriş Yap",
  "OR CONNECT USING": "VEYA BAĞLANTI KUR",
  "Don't have an account?": "Hesabınız yok mu?",
  "Sign up": "Kayıt Ol",
  "Welcome": "Hoş Geldiniz",
  "Your welcome message": "Hoş geldin mesajınız",
  "User Name": "Kullanıcı Adı",
  "Enter User Name..": "Kullanıcı Adı Girin..",
  "Email Address": "E-posta Adresi",
  "Enter Valid Email..": "Geçerli E-posta Girin..",
  "Confirm Password": "Şifreyi Onayla",
  "Your cart is empty": "Sepetiniz boş",
  "Looks like you didn": "Görünüşe göre yapmadınız",
  "Cart": "Sepet",
  "Remove Items": "Öğeleri Kaldır",
  "Total": "Toplam",
  "products": "ürünler",
  "Checkout": "Ödeme",
  "Latest arrival": "Son Gelenler",
  "Categories": "Kategoriler",
  "Search": "Arama",
  "No Product Found": "Ürün Bulunamadı",
  "Sucsecc": "Başarı",
  "Order has been requseted sucseccfully": "Sipariş başarıyla talep edildi",
  "My Orders": "Siparişlerim",
  "In Cart": "Sepette",
  "Add to cart": "Sepete Ekle",
  "About this item": "Bu ürün hakkında",
  "In": "İçinde",
  "Please login to have ultimate access": "Tam erişim için lütfen giriş yapın",
  "General": "Genel",
  "All Orders": "Tüm Siparişler",
  "Wishlist": "İstek Listesi",
  "ViewedRecently": "Son Görüntülenenler",
  "Settings": "Ayarlar",
  "Dark Mode": "Karanlık Mod",
  "Light Mode": "Aydınlık Mod",
  "Languages": "Diller",
  "Logout": "Çıkış Yap",
  "Are you sure": "Emin misiniz",
  "Select Language": "Dil Seçin",
  "English": "İngilizce",
  "Turkish": "Türkçe",
  "Arabic": "Arapça",
  "Your wishlist is empty": "İstek listeniz boş",
  "Looks like you didnot have wishlist": "Görünüşe göre istek listeniz yok",
  "Home": "Ana Sayfa",
  "Profile": "Profil",
  'No Result Found': 'Sonuç Bulunmadı',
  'Order ID:': 'Order ID',
  'User:': 'User',
  'Date:': 'Date',
  'Total Price:': 'Total Price',
  'Status:': 'Status',
  'Products:': 'Products',
  'Pending:': 'Beklemede',
  'Processing:': 'İşleniyor',
  'Shipped:': 'Gönderildi',
  'Delivered:': 'Teslim Edildi',
  'Cancelled:': 'İptal edildi',
};
