// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLFrwRt_qnVhTmOmB06WGNpjethuNZuq0',
    appId: '1:611668129666:web:cbe1f84bae669ad9e1419b',
    messagingSenderId: '611668129666',
    projectId: 'shophadi-ec794',
    authDomain: 'shophadi-ec794.firebaseapp.com',
    storageBucket: 'shophadi-ec794.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnDXdUj5jm8QN0ktu4dIDonG9QO19pXSk',
    appId: '1:611668129666:android:7f17192d90a56028e1419b',
    messagingSenderId: '611668129666',
    projectId: 'shophadi-ec794',
    storageBucket: 'shophadi-ec794.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLFrwRt_qnVhTmOmB06WGNpjethuNZuq0',
    appId: '1:611668129666:web:f01f541b4b7ba4ffe1419b',
    messagingSenderId: '611668129666',
    projectId: 'shophadi-ec794',
    authDomain: 'shophadi-ec794.firebaseapp.com',
    storageBucket: 'shophadi-ec794.appspot.com',
  );

}